# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

languages:
  en:
    contentDir: content/en
    baseURL: 'https://hamedentist.com/en' # Website URL
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    params:
    subtitle: Reservation or Reserving an Appointment with Dr.Hamed
    title: Dr.Hamed Alghamdi - Dentist
    weight: 1
    
  ar:
    contentDir: content/ar
    baseURL: 'https://hamedentist.com/ar' # Website URL
    disabled: false
    languageCode: ar
    languageDirection: rtl
    languageName: Arabic
    params:
    subtitle: Reservation or Reserving an Appointment with Dr.Hamed
    title: Dr.Hamed Alghamdi - Dentist
    weight: 2

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
