[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.119.0"
  HUGO_ENABLEGITINFO = "false"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo"

[context.branch-deploy]
  command = "hugo"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
